apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    app: server
    lightfoot: disable
spec:
  containers:
    - name: server-container
      image: server:v1
      ports:
        - containerPort: 50051
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
        requests:
          cpu: "200m"
          memory: "256Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    app: client
    lightfoot: enable
spec:
  containers:
    - name: client-container
      image: client:v1
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
