apiVersion: v1
kind: Pod
metadata:
  name: watcher-pod
  labels:
    app: watcher
spec:
  containers:
    - name: watcher
      image: localhost:5000/watcher
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
