apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lightfoot-daemon
  labels:
    app: lightfoot-daemon
spec:
  selector:
    matchLabels:
      app: lightfoot-daemon
  template:
    metadata:
      labels:
        app: lightfoot-daemon
    spec:
      containers:
      - name: lightfoot
        image: localhost:5000/lightfoot
        ports:
        - containerPort: 12000
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "NET_ADMIN"]
          allowPrivilegeEscalation: true
        volumeMounts:
        - mountPath: /host
          name: host-root
          readOnly: true
      volumes:
      - hostPath:
          path: /
          type: Directory
        name: host-root
      hostPID: true
