# Create namespace for ebpf-trasport-monitoring
kind: Namespace
apiVersion: v1
metadata:
  name: etm
  labels:
    name: etm
---
{{- if eq .Values.etm_sink "gcp"}}
apiVersion: v1
kind: Secret
metadata:
  name: gcp-secret
  namespace: etm
type: Opaque
data:
  gcp_creds.json: {{  .Values.etm_json_secret | b64enc }} 
---
{{ end }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lightfoot-daemon
  namespace: etm
  labels:
    app: lightfoot-daemon
spec:
  selector:
    matchLabels:
      app: lightfoot-daemon
  template:
    metadata:
      namespace: etm
      labels:
        app: lightfoot-daemon
    spec:
      containers:
      - name: lightfoot
        image: localhost:5000/lightfoot
        args:
        - "--log_level={{.Values.log_level}}"
        {{- if eq .Values.etm_sink "file" }}
        - "--file_log"
          {{- if .Values.etm_file_sink }}
        - "--file_log_location={{ .Values.etm_file_sink }}"
          {{- end }}
        {{- else if eq .Values.etm_sink "gcp"}}
        - "--opencensus_log"
        - "--gcp_project={{- required "Project id is required" .Values.etm_gcp_project }}"
        - "--gcp_creds=/etc/secret/gcp_creds.json"
        {{ end }}
        ports:
        - containerPort: 12000
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "NET_ADMIN"]
          allowPrivilegeEscalation: true
        volumeMounts:
        - mountPath: /host
          name: host-root
          readOnly: true
        {{- if eq .Values.etm_sink "gcp"}}
        - name: my-secret-volume
          mountPath: "/etc/secret"
        {{ end }}
      volumes:
      - hostPath:
          path: /
          type: Directory
        name: host-root
      {{- if eq .Values.etm_sink "gcp" }}
      - name: my-secret-volume
        secret:
          secretName: gcp-secret 
      {{ end }}
      hostPID: true
---
# Creating a service account for the watcher
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-viewer
  namespace: etm
---
# Creating a role for the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-viewer-role
rules:
- apiGroups: [""] # "" represents the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"] 
---
# Binding the role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-viewer-binding
subjects:
  - kind: ServiceAccount
    name: pod-viewer
    namespace: etm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-viewer-role
---
apiVersion: v1
kind: Pod
metadata:
  name: watcher-pod
  namespace: etm
  labels:
    app: watcher
spec:
  containers:
    - name: watcher
      image: localhost:5000/watcher
      args: 
      - "--stderrthreshold={{.Values.log_level}}"
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
  serviceAccountName: pod-viewer
